### ISSUE TITLE
Git commit not created Error: Command failed: git commit -m "Initialize project using Create React App"

### ISSUE THREAD

**Issue by guoweiTang** [poeticloud/cra-template-rack-typescript#1]
```
Git commit not created Error: Command failed: git commit -m "Initialize project using Create React App"
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at tryGitCommit (/home/ice/project/my-rack-ts2/node_modules/react-scripts/scripts/init.js:62:5)
    at module.exports (/home/ice/project/my-rack-ts2/node_modules/react-scripts/scripts/init.js:352:25)
    at [eval]:3:14
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:309:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 4154,
  stdout: null,
  stderr: null
}
Removing .git directory...
```

**Comment by guoweiTang** [comment]
Apparently you can solve it in two ways:

1. Making the initial git global config

```
$ git config --global user.name "Ice"
$ git config --global user.email ice@example.com
```

2. Repository creation fails, if there are git hooks attached to it. Workaround: disable initial husky configuration.

Tried that?
